### ISSUE TITLE
content-service unable to start in CI

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-content-service#88]
Content-service crashes if it cannot find `reason.md` in `/rules-content/external/rules/rule_name/reason.md`. It seems some rules can have `reason.md` in subdirectories.

Actual result:

Log excerpt:
```
{"level":"error","error":"open /rules-content/external/rules/ocp_version_end_of_life/reason.md: no such file or directory","time":"2020-06-29T06:51:09Z","message":"No rules directory"}
```

Expected result:
Content-service should account such cases and not to crash.

**Comment by joselsegura** [comment]
This problem should not happen in the rules repository being parsed were ok, but we need to protect against this kind of errors.

I will take this one and simply ignore every rule that doesn't contain some required field (or if it is in a different location). Some error log about the directory not being parsed should be printed too.
